language: python
cache:
  pip
python:
  # - "2.7"
  - "3.5"
# command to install dependencies
install: 
  "pip install pandas"
# # command to run tests
script: 
  python module9_challenge_2.py submission.py



notifications:
  email:
    on_success: never
    on_failure: never
